let handler = async (m, { conn }) => {

const frases = [
"😈 Eres más inútil que botón de like en WhatsApp",
"💀 Cállate que ni tu sombra te sigue",
"🔥 Hablas pura mamada sin sentido",
"🤡 Pareces chiste mal contado",
"😤 Mejor ni opines que la cagas más",
"💩 Eres un bug andante",
"🐀 Más falso que tus ganas de cambiar",
"🥴 Das pena ajena compa",
"🧠 Te falla el cerebro o qué",
"😹 Ni tú te crees lo que dices",
"💀 Eres puro ruido y nada de contenido",
"😈 Naces otra vez y la vuelves a cagar",
"🔥 Hablas y baja el IQ del grupo",
"🤡 Te esfuerzas o así eres naturalmente pendejo",
"💩 Eres la definición de fracaso premium",

// 🔥 TUS FRASES
"Ya mejor ni hables, la cagas solo",
"Eres puro estorbo con patas",
"Hablas y todo se arruina",
"Tu cerebro parece apagado",
"Eres más inútil que excusa mala",
"Ni con ganas mejoras",
"Das más pena que cualquier cosa",
"Eres puro intento fallido",
"Tu lógica no existe",
"Ni tú sabes qué dices",
"Eres más molesto que ruido constante",
"Tu presencia cansa",
"Eres puro error",
"Ni con ayuda destacas",
"Eres más lento que carga infinita",
"Tu nivel da tristeza",
"Eres puro relleno inútil",
"Hablas y la cagas fácil",
"Ni en sueños mejoras",
"Eres más innecesario que tutorial básico",
"Tu cerebro no responde",
"Eres puro fallo constante",
"Das más cringe que gracia",
"Ni tú te aguantas",
"Eres más inútil que botón viejo",
"Tu lógica está rota",
"Eres puro estorbo",
"Ni con esfuerzo mejoras",
"Eres más molesto que bug",
"Tu nivel es pésimo",
"Eres puro intento barato",
"Das más pena que respeto",
"Ni tú entiendes lo que haces",
"Eres más lento que sistema viejo",
"Tu cerebro está en pausa",
"Eres puro problema",
"Ni en grupo encajas",
"Eres más innecesario que app vacía",
"Tu lógica falla siempre",
"Eres puro ruido",
"Das más risa que sentido",
"Ni con suerte mejoras",
"Eres más inútil que botón falso",
"Tu presencia baja todo",
"Eres puro error constante",
"Ni tú te crees",
"Eres más molesto que anuncio largo",
"Tu nivel es bajo",
"Eres puro estorbo constante",
"Eres más lento que señal mala",
"Tu lógica no sirve",
"Eres puro intento fallido",
"Das más pena que risa",
"Ni tú te soportas",
"Eres más inútil que tutorial viejo",
"Tu cerebro no conecta",
"Eres puro fallo humano",
"Eres más innecesario que error repetido",
"Tu nivel es triste",
"Eres puro ruido sin sentido",
"Das más cringe que respeto",
"Ni tú sabes qué haces",
"Eres más lento que internet viejo",
"Tu lógica está mal",
"Eres puro estorbo",
"Ni en fácil destacas",
"Eres más molesto que notificación constante",
"Tu cerebro no procesa",
"Eres puro intento",
"Das más pena que orgullo",
"Ni tú entiendes",
"Eres más inútil que botón roto",
"Tu presencia estorba",
"Eres puro fallo constante",
"Eres más lento que carga vieja",
"Tu lógica no existe",
"Eres puro ruido",
"Das más risa que lógica",
"Eres más innecesario que relleno malo",
"Tu nivel es pésimo",
"Eres puro intento fallido",
"Eres más molesto que error constante",
"Tu cerebro no funciona",
"Eres puro estorbo",
"Eres más lento que sistema caído",
"Tu lógica falla siempre",
"Eres puro problema",
"Eres más inútil que app inútil",
"Tu presencia cansa",
"Eres puro fallo",
"Eres más innecesario que intro larga",
"Tu nivel es bajo",
"Eres puro ruido constante",
"Eres más lento que conexión mala",
"Tu lógica está rota",
"Eres puro intento",
"Eres más molesto que spam",
"Tu cerebro no responde",
"Eres puro estorbo",
"Eres más inútil que botón decorativo",
"Tu nivel da risa",
"Eres puro fallo constante",
"Eres más lento que actualización",
"Tu lógica no sirve",
"Eres puro ruido",
"Eres más innecesario que tutorial básico",
"Tu cerebro no conecta",
"Eres puro intento fallido",
"Eres más molesto que bug constante",
"Tu nivel es pésimo",
"Eres puro estorbo constante",
"Eres más lento que sistema viejo",
"Tu lógica falla",
"Eres puro ruido",
"Eres más inútil que botón falso",
"Tu presencia estorba",
"Eres puro fallo",
"Eres más molesto que error repetido",
"Tu cerebro no funciona",
"Eres puro intento",
"Eres más lento que carga eterna",
"Tu lógica no existe",
"Eres puro estorbo",
"Eres más innecesario que app vacía",
"Tu nivel es bajo",
"Eres puro fallo constante",
"Eres más inútil que tutorial viejo",
"Tu cerebro no procesa",
"Eres puro intento fallido",
"Eres más molesto que anuncio repetido",
"Tu nivel da pena",
"Eres puro estorbo",
"Eres más lento que conexión mala",
"Tu lógica está rota",
"Eres puro ruido",
"Eres más inútil que botón roto",
"Tu presencia cansa",
"Eres puro fallo constante",
"Eres más molesto que spam constante",
"Tu cerebro no conecta",
"Eres puro intento",
"Eres más innecesario que error viejo",
"Tu nivel es pésimo",
"Eres puro estorbo",
"Eres más lento que sistema viejo",
"Tu lógica falla",
"Eres puro ruido",
"Eres más inútil que botón falso",
"Eres puro fallo",
"Eres más molesto que error constante",
"Eres puro intento fallido",
"Eres más lento que carga eterna",
"Tu lógica no sirve",
"Eres puro estorbo",
"Eres más innecesario que tutorial básico",
"Eres puro ruido",
"Eres puro fallo constante"
];

const frase = frases[Math.floor(Math.random() * frases.length)];

await conn.sendMessage(m.chat, {
    text: frase
}, { quoted: m });

}

handler.help = ['randoms']
handler.command = ['randoms']
handler.tags = ['fun']

export default handler;